AllCops:
  DefaultFormatter: fuubar

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 100

Naming/UncommunicativeMethodParamName:
  Enabled: false
