AllCops:
  DefaultFormatter: fuubar
  CacheRootDirectory: .rubocop/cache

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 100

Naming/UncommunicativeMethodParamName:
  Enabled: false
